const Compdata = [
    {
        id:1,
        username:  "Sam Altman",
        penmail: "samaltman123@gmail.com",
        risklvl: "Medium",
        queuepen: "Flagged",
        pendays: "14 days",
        pendate: "12 Oct, 2023",
        penchcek : "Neil",
        compmail: "Neil@onjuno.com",
    },
    {
        id:2,
        username:  "Samar Choubey",
        penmail: "samarchoubey123@gmail.com",
        risklvl: "High",
        queuepen: "Closed",
        pendays: "14 days",
        pendate: "12 Oct, 2023",
        penchcek : "Pratik",
        compmail: "pratik@onjuno.com",
    },
    {
        id:3,
        username:  "Adarsh Panikar",
        penmail: "adarsh@onjuno.com",
        risklvl: "Low",
        queuepen: "Flagged",
        pendays: "14 days",
        pendate: "12 Oct, 2023",
        penchcek : "Prashanth",
        compmail: "prashanth@onjuno.com",
    },
    {
        id:4,
        username:  "Pratik Shetty",
        penmail: "pratik3@gmail.com",
        risklvl: "High	",
        queuepen: "Cleared",
        pendays: "15 days",
        pendate: "12 Oct, 2023",
        penchcek : "Rasleen Kaur",
        compmail: "rasleen@onjuno.com",
    },
    {
        id:5,
        username:  "Elon Musk",
        penmail: "elon@twitterceo.com",
        risklvl: "Low",
        queuepen: "Flagged",
        pendays: "15 days",
        pendate: "12 Oct, 2023",
        penchcek : "Pratik",
        compmail: "pratik@onjuno.com",
    },
    {
        id:6,
        username:  "Trina Kundu",
        penmail: "trina@onjuno.com",
        risklvl: "Low",
        queuepen: "Flagged",
        pendays: "14 days",
        pendate: "12 Oct, 2023",
        penchcek : "Varun Deshpande",
        compmail: "varun@onjuno.com",
    },
]


export default Compdata;