const Sdata = [
    {
        id:1,
        username:  "Sam Altman",
        penmail: "samaltman123@gmail.com",
        risklvl: "Medium",
        queuepen: "IP change",
        pendays: "4 days",
        pendate: "12 Oct, 2023",
        penchcek : "Yes",
        pendatelst: "23 Aug, 2023",
    },
    {
        id:2,
        username:  "Samar Choubey",
        penmail: "samarchoubey123@gmail.com",
        risklvl: "High",
        queuepen: "Closed",
        pendays: "4 days",
        pendate: "12 Oct, 2023",
        penchcek : "No",
    },
    {
        id:3,
        username:  "Adarsh Panikar",
        penmail: "adarsh@onjuno.com",
        risklvl: "Low",
        queuepen: "IP change",
        pendays: "4 days",
        pendate: "12 Oct, 2023",
        penchcek : "No",
    },
    {
        id:4,
        username:  "Pratik Shetty",
        penmail: "pratik3@gmail.com",
        risklvl: "High	",
        queuepen: "FIFO",
        pendays: "5 days",
        pendate: "12 Oct, 2023",
        penchcek : "No",
    },
    {
        id:5,
        username:  "Elon Musk",
        penmail: "elon@twitterceo.com",
        risklvl: "Low",
        queuepen: "FIFO",
        pendays: "5 days",
        pendate: "12 Oct, 2023",
        penchcek : "Yes",
        pendatelst: "12 Sep, 2023",
    },
    {
        id:6,
        username:  "Trina Kundu",
        penmail: "trina@onjuno.com",
        risklvl: "Low",
        queuepen: "FIFO",
        pendays: "5 days",
        pendate: "12 Oct, 2023",
        penchcek : "Yes",
        pendatelst: "12 Sep, 2023",
    },
]

export default Sdata;